# Generated by Django 3.1.2 on 2020-10-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201013_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emailconfirmation',
            new_name='EmailConfirmationToken',
        ),
    ]
