# Generated by Django 3.1.2 on 2020-10-14 12:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201014_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash_precedent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Precedent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('positive', models.SmallIntegerField(choices=[(1, 'positive'), (-1, 'negative')])),
                ('importance', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
