# Generated by Django 3.1.2 on 2020-10-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201017_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash_precedent_integer',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
