# Generated by Django 3.1.2 on 2020-10-19 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_hash_precedent_integer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precedent',
            old_name='positive',
            new_name='attitude',
        ),
        migrations.AlterUniqueTogether(
            name='precedent',
            unique_together={('user', 'name')},
        ),
    ]
