# Generated by Django 3.1.2 on 2020-10-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201019_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hash_precedent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hash_precedent_integer',
        ),
    ]
