version: '3'

services:
  parser:
    build:
      context: .
      dockerfile: Dockerfile
    image: parser
    container_name: parser
    command: poetry run python parser.py
    volumes:
      - .:/home/python/app

networks:
  default:
    external:
      name: test_sibdev_default
