[tool.poetry]
name = "parser"
version = "0.1.0"
description = "parser"
authors = ["bro.agency"]

[tool.poetry.dependencies]
python = ">=3.9 <4"
aiofile = "^3.1.1"
peewee-async = "^0.7.1"
aiopg = "^1.0.0"


[tool.poetry.dev-dependencies]

[build-system]

